kind: pipeline
type: docker
name: frontend_dev

steps:
  - name: lint&test
    image: node
    commands:
      - npm install
      - npm run lint
  
  - name: build image
    image: appleboy/drone-ssh
    settings:
      host:
        from_secret: ssh_host
      username: 
        from_secret: ssh_name
      key:
        from_secret: ssh_key
      port: 22
      timeout: 60s
      command_timeout: 2m
      script:
        - cd ~/app/url-shortener
        - git checkout master
        - git pull origin master
        - sudo docker build -f docker/dockerfile . -t frontend:latest
        - cd ~/nginx
        - sudo docker-compose -f docker-compose.yml up -d 

  - name: discord notification
    image: appleboy/drone-discord
    settings:
      webhook_id: 
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: >
        {{#success build.status}}
          ✅ Build #{{build.number}} of `{{repo.name}}` succeeded.
          📝 Commit by {{commit.author}} on `{{commit.branch}}`:
          ```
          {{commit.message}}
          ```
          🌐 {{ build.link }}
        {{else}}
          ❌ Build #{{build.number}} of `{{repo.name}}` failed.
          📝 Commit by {{commit.author}} on `{{commit.branch}}`:
          ```
          {{commit.message}}
          ```
          🌐 {{ build.link }}
        {{/success}}

trigger:
  branch:
    - master
  event:
    - push